# Generated by Django 4.2.16 on 2026-05-28 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_alter_specialization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_alter_appointmentpayment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFinanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_subscriptions', models.IntegerField(default=0)),
                ('starter_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('growth_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('enterprise_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_clinics', models.IntegerField(default=0)),
                ('churned_clinics', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_finance_summary',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('plan', models.CharField(max_length=20)),
                ('billing_cycle', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(choices=[('stripe', 'Stripe (Card)'), ('manual_card', 'Manual Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='stripe', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=200)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments', to='clinics.clinic')),
            ],
            options={
                'db_table': 'platform_subscription_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('walkin_patient_name', models.CharField(blank=True, max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(max_length=30)),
                ('reference_no', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_transactions', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='clinics.clinic')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinic_transactions',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicPayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mtn_momo', 'MTN Mobile Money'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('orange_money', 'Orange Money'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cash', 'Cash Only'), ('multiple', 'Multiple Methods')], max_length=30)),
                ('account_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, help_text='Bank account or mobile number', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('stripe_account_id', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Payment instructions shown to patients')),
                ('booking_fee_default', models.DecimalField(decimal_places=2, default=0, help_text='Default booking fee for this clinic', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to='clinics.clinic')),
            ],
            options={
                'db_table': 'clinic_payout_accounts',
            },
        ),
    ]
