# Generated by Django 4.2.16 on 2026-06-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_specialization_options_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformfinancesummary',
            options={},
        ),
        migrations.AlterModelTable(
            name='platformfinancesummary',
            table=None,
        ),
        migrations.CreateModel(
            name='PlatformCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_to_clinic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.clinic')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='finance.clinictransaction')),
            ],
            options={
                'db_table': 'platform_commissions',
            },
        ),
    ]
