# Generated by Django 4.2.16 on 2026-05-18 14:59

import apps.clinics.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logos/')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('approval_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('subscription_plan', models.CharField(choices=[('trial', 'Free Trial'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('subscription_status', models.CharField(choices=[('pending', 'Pending'), ('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_expiry', models.DateField(blank=True, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_holder', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_clinics', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_clinics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinics',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'specializations',
            },
        ),
        migrations.CreateModel(
            name='ClinicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('registration_cert', 'Registration Certificate'), ('license', 'Medical License'), ('tax_cert', 'Tax Certificate'), ('other', 'Other')], max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.clinics.models.clinic_doc_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clinics.clinic')),
            ],
            options={
                'db_table': 'clinic_documents',
            },
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.specialization')),
            ],
            options={
                'db_table': 'clinic_services',
                'unique_together': {('clinic', 'specialization')},
            },
        ),
    ]
