# Generated by Django 4.2.16 on 2026-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='specialization',
            name='common_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='example_symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='icon',
            field=models.CharField(default='🏥', max_length=10),
        ),
        migrations.AddField(
            model_name='specialization',
            name='when_to_visit',
            field=models.TextField(blank=True),
        ),
    ]
