# Generated by Django 4.2.16 on 2026-05-18 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name_snapshot', models.CharField(blank=True, max_length=150)),
                ('condition_description', models.TextField()),
                ('preferred_date', models.DateField()),
                ('preferred_time_of_day', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=20)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('proposed_time_slot', models.TimeField(blank=True, null=True)),
                ('proposal_message', models.TextField(blank=True)),
                ('proposal_sent_at', models.DateTimeField(blank=True, null=True)),
                ('patient_response', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=20)),
                ('patient_response_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('confirmed_time_slot', models.TimeField(blank=True, null=True)),
                ('booking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_fee_currency', models.CharField(default='USD', max_length=10)),
                ('rejection_note', models.TextField(blank=True)),
                ('doctor_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('proposed', 'Slot Proposed'), ('accepted', 'Patient Accepted'), ('awaiting_payment', 'Awaiting Payment'), ('payment_submitted', 'Payment Submitted'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=30)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('receptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='AppointmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointments.appointment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment_payments',
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'status'], name='appointment_clinic__13de9b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient'], name='appointment_patient_75a4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'confirmed_date'], name='appointment_doctor__0be588_idx'),
        ),
    ]
