# Generated by Django 4.2.16 on 2026-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentpayment',
            name='method',
            field=models.CharField(choices=[('card', '💳 Credit / Debit Card (Visa, Mastercard, Amex)'), ('mtn_momo', '📱 MTN Mobile Money'), ('mpesa', '📱 M-Pesa'), ('airtel_money', '📱 Airtel Money'), ('orange_money', '📱 Orange Money'), ('tigo_pesa', '📱 Tigo Pesa'), ('bank_transfer', '🏦 Bank Transfer'), ('paypal', '🅿️ PayPal'), ('cash', '💵 Cash (pay at clinic)'), ('other', '🔄 Other')], max_length=20),
        ),
    ]
